version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - lcobucci
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
